[design]
mode = "displace"
stabilization = "finkeel"
hull = "mono"

[composition]
ballast_percentage = 35
alu_percentage = 3
gfk_percentage = 40
wood_percentage = 2
engine_percentage = 3
amenity_percentage = 15